Add nanogpt and training function
ChrisHayduk/Recurrent-Neuron-Transformer pull request #22
Opened 2023-12-07 04:48 UTC by sophgen

Adapted NanoGPT and make modifications in order to work with TextDataLoader classes

2023-12-07 05:38 UTC, nateburley requested changes
Looks good overall! The only possible change I see is that we might need to tweak the training loop though to split the chunks into sequences of length context_window, and then iterate through the chunk

2023-12-07 05:38 UTC, nateburley commented on experiments/reconstruct_shakespeare.py
> +    parser.add_argument("--nlayer", type=int, default=12, help="Number of layers for NanoGPT")
Let's get rid of num_encoder_layers and num_decoder_layers and just substitute this in to make it consistent

2023-12-07 05:38 UTC, nateburley commented on experiments/reconstruct_shakespeare.py
> +    parser.add_argument("--dropout", type=float, default=0.0, help="Drop out")
Dropout is in already, might need to merge with main

2023-12-07 05:38 UTC, nateburley commented on utils/training.py
> +def train_nanogpt(model, device, train_data_loader, val_data_loader, max_iters, batch_size):
Where does the chunking and context window splitting happen in the training function?

2023-12-07 05:38 UTC, nateburley commented on utils/training.py
> +                X, Y = get_batch(split)
I think we need to add the logic here to split the chunk into a piece of context_size, right?

2023-12-08 03:24 UTC, sophgen commented
Thanks so much @nateburley  for the comments, I will close this one and create a new PR from latest main. Thanks!

2023-12-08 03:24 UTC, closed without merging